/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package atelier9;

import java.util.Scanner;

public class App {

    public static void main(String[] args) 
    {
        station_meteo = new weather();

        // TODO: effectuer une boucle infinie
        // qui effectue la lecture d'un nom de ville sur la ligne de commande
        // ce lien pourrait vous être utile: https://www.w3schools.com/java/java_user_input.asp
        // le programme se termine lorsque le nom de ville entrée est vide
        // utiliser la méthode getWeather de la variable station_meteo pour obtenir 
        // les prévisions météorologiques de la ville qui vous intéresse
    }
}
